#!/bin/sh

if [ -z $1 ]; then
				echo no db
				exit 1
fi
if [ -z $2 ]; then
				echo no id
				exit 1
fi

#json=`./create_json $3`

#eval "curl -X PUT localhost:5984/$1/$2 -d'`printf %s $json`'"
eval "curl -X PUT localhost:5984/$1/$2 -d'$3'"

